services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=frequencyusers'
      - 'MYSQL_ROOT_PASSWORD=041t7CXdaA`qYr[sp|'
      - 'MYSQL_ROOT_HOST=%'
    ports:
      - '3307:3306'
    networks:
      - backend

networks:
  backend:
    driver: bridge
